"""
Tests for src/pipeline/selection.py -- selecting the submission corpus from
Builderr's frozen universe file. Deterministic (seeded) so the same manifest
can be regenerated byte-for-byte, matching the "reproducible setup" hard gate.
"""
from src.pipeline.selection import select_companies

UNIVERSE = {str(900000000 + i): {"organisation_number": str(900000000 + i)} for i in range(20)}


def test_selects_the_requested_count():
    selected = select_companies(UNIVERSE, count=5, seed=1)
    assert len(selected) == 5
    assert len(set(selected)) == 5
    assert all(org in UNIVERSE for org in selected)


def test_same_seed_is_deterministic():
    first = select_companies(UNIVERSE, count=5, seed=42)
    second = select_companies(UNIVERSE, count=5, seed=42)
    assert first == second


def test_different_seed_can_select_differently():
    first = select_companies(UNIVERSE, count=5, seed=1)
    second = select_companies(UNIVERSE, count=5, seed=2)
    assert first != second


def test_count_larger_than_universe_returns_everything():
    selected = select_companies(UNIVERSE, count=1000, seed=1)
    assert sorted(selected) == sorted(UNIVERSE.keys())
